name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install kicad build dependencies
        run: sudo apt-get install cmake libgl-dev libglew-dev libglm-dev libcurl4-openssl-dev libcairo2-dev libboost-dev swig libwxgtk3.0-gtk3-dev libgtk-3-dev libssl-dev libboost-test-dev libboost-filesystem-dev build-essential libpython3-dev

      - uses: actions/cache@v2
        with:
          path: |
            /tmp/bazel-cache
          key: ${{ runner.os }}-bazelcache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-bazelcache-

      - uses: actions/checkout@v2

      - run: bazel build //examples/... --disk_cache=/tmp/bazel-cache
